spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/quiz
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create   # WICHTIG für Testphase
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always